### PR TITLE
Closes #269: Do not show try this when project does not have /hello p…

### LINKED ISSUE #269: Don't show "try this: curl http://127.0.0.1:10010/hello?name=Scott" when project doesn't have /hello path anymore

### PR DESCRIPTION
**Pull request by jsdevel**
…ath.

### CODE REVIEW

**Comment by theganyo** [comment]
@jsdevel Accepting your earlier PR created a conflict in this one.

**Comment by jsdevel** [comment]
let me resolve

**Comment by jsdevel** [comment]
done

**Comment by theganyo** [comment]
Thanks. But these changes also fail testing.

**Comment by jsdevel** [comment]
Sorry about that.  Small oversight.  Gotta love travis!

Should be good now.

**Comment by theganyo** [comment]
Yup. That should work. Thanks!

**Pull request merged**
