### PR TITLE
update all skeletons to latest versions and fix async test race-condition

### PR DESCRIPTION
**Pull request by micmro**
I've updated all 'connect'-based framework dependencies to their latest versions (inc. `swagger-node-runner` v0.7.0 wrapper):
- expess
- connect
- hapi
- restify

added `swagger_params_parser` to [fix `swagger-node-runner` >=0.6.0 for Sway](https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.0)

To test this I manually copied the `project-skeletons` files into generated projects and ran tests and a manual run.

This will close e.g. #416

### CODE REVIEW

**Comment by micmro** [comment]
It seem like something seems to be wrong with the sails test and the connect tests - if I remove the sails test it succeeds vis-a-vie. There seems to be some cross-dependency.

Do you have any suggestion for fixes?

**Comment by micmro** [comment]
Hi @fehguy, would you have any suggestions regarding the failing tests? I can't figure out why thy would fail in this pattern.

**Comment by micmro** [comment]
I managed to fix the test, but it looks the latest hapi version does not support node v0.12 anymore (in strict mode at least), due to the use of the `const`.

Should I go with an older version or do you have any plans to change the test runners?

**Comment by fehguy** [comment]
Hi @micmro I think we should update the tested support to be minimum 4.x.  If you want to update the travis file we can merge it.  Thanks again!

**Comment by micmro** [comment]
Ok updated it. Is it possible to create a release for this?

**Comment by micmro** [comment]
Hi @fehguy I've made the changes to the travis file. Are there any other blocker for this?

**Pull request merged**
