### PR TITLE
npm@3 support: fix swagger-editor dir path. Fixes #351

### LINKED ISSUE #351: "swagger project edit" support for npm@3 and local install
I would prefer to keep my dependencies local to the project. Thus, I install swagger as a local devDependency and then hook up swagger via npm scripts:

```json
"scripts": {
  "edit": "swagger project edit",
  "test": "swagger project test"
}
```

This works fine for npm@v2, but does not work for npm@3 because of the way packages are nested (or rather, not nested) in `node_modules`.

The problem lines are here:

* https://github.com/swagger-api/swagger-node/blob/3a000dcc7d0c3c907b60dc0f3efc8e04a3cb3b04/config/index.js#L27
* https://github.com/swagger-api/swagger-node/blob/3a000dcc7d0c3c907b60dc0f3efc8e04a3cb3b04/config/index.js#L35

`node_modules` is no longer nested with npm@3, thus those paths do not exist, which results in a "Cannot GET /" error from connect. 

I'm unclear of an elegant solution here.

### PR DESCRIPTION
**Pull request by badsyntax**
See issue #351

### CODE REVIEW

**Comment by badsyntax** [comment]
BTW tests are failing on master, not due to this change.

**Comment by fehguy** [comment]
Hi, yes, there was a dependency change which has caused master to start failing.  Will get that resolved before merging your PR.

**Comment by badsyntax** [comment]
Just curious, has development stopped on swagger-node?

**Comment by webron** [comment]
@badsyntax we do our best, but sometimes things get delayed beyond what we wish them too. Apologies for the late response here. For the sake of completeness, can you please rebase your PR? We fixed the build and that should make the build of your PR to fix as well.

**Comment by at15** [comment]
@fehguy @badsyntax  I guess this pr can be closed, since #369 is already merged.

**Comment by badsyntax** [comment]
@at15 a polite request for rebase then a merge of this PR would have been the better approach.

**Pull request closed without merging**
