### PR TITLE
Fixes Issue #288 `project swagger test` does not exit with the correct exit code

### PR DESCRIPTION
**Pull request by henningvs**
Fixes Issue #288 by rebasing change done in #335 to current master commit.

Replaced callback by process.exit to comply with ci tools

### CODE REVIEW

**Comment by henningvs** [comment]
This seems to be the same error which is currently appearing in the master branch.

**Comment by fehguy** [comment]
Travis is not happy :(

**Comment by henningvs** [comment]
@fehguy I think it happens because of this line:

`>> Overwrite this one and show the next? Conflict on hello-test.js. Overwrite? (answer 'h' for help): (Yanxh) ? Conflict on hello-test.js. Overwrite? (answer 'h' for help): (Yanxh) [ERROR] (node:1825) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier`

**Comment by henningvs** [comment]
Fixed the broken travis build by upgrading inquirer version in package.json from 0.10.0 to 1.2.3. It is not possible to use the newest inquirer version (2.0.0), as they dropped the support for node 0.12.

The issue which broke travis is described here: https://github.com/SBoudrias/Inquirer.js/issues/290.

**Comment by fehguy** [comment]
thanks @henningvs

**Comment by calvn** [comment]
Will there be a release cut any time soon? It seems that 0.7.5 is the latest version, which was released ~1 year ago.

**Comment by fehguy** [comment]
Yes, we're working on it right now.

**Comment by aryzle** [comment]
👍 please make a release

**Comment by ChrisLahaye** [comment]
Since this has not yet been released, you can use the following to acquire a non-zero exit code on errors.

```bash
project swagger test | tee out.log && ! grep -q -E "[0-9]+ failing" out.log
```

If you are monitoring the exit code of the shell:
```bash
project swagger test | tee out.log && grep -q -E "[0-9]+ failing" out.log && exit 1
```

**Comment by henningvs** [comment]
Or if you are willing to touch your dependencies you could also include the git repository directly as a dependency in the package.json

`"swagger": "git://github.com/swagger-api/swagger-node.git#b6d0d41"`

**Pull request merged**
