### PR TITLE
Minor fixes to README

### PR DESCRIPTION
**Pull request by theopak**
Great project! There were a couple broken links in the readme, and it was impossible to copy-paste the shell commands out of it because they were embedded images with no alt text. This PR makes them text instead.

### CODE REVIEW

**Comment by theopak** [comment]
(I see now that #225 already fixes the links)

**Comment by theganyo** [comment]
Also, sadly, accepting #225 broke this PR...  can you fix the conflicts? Thanks!

**Comment by theopak** [comment]
Ok

**Comment by theganyo** [comment]
Thanks!

**Pull request merged**
