### PR TITLE
Converter command

### PR DESCRIPTION
**Pull request by noahdietz**
@theganyo after struggling with rewire for too long, here is the ```swagger convert``` command and basic tests for both this and ```swagger validate```

### CODE REVIEW

**Comment by theganyo** [comment]
Thank you! Just curious: Is there any reason why you chose to add and use the rewire package instead of the already included proxyquire?

**Comment by mohsen1** [comment]
I advised for using rewire since Noah worked with it in the test-templates project. We were not familiar with proxyquire so we decided to go with rewire. Now that I looked at proxyquire documentation it seems it's API is very similar to rewire and it might be possible to replace all rewire calls with proxyquire.

**Comment by noahdietz** [comment]
@theganyo would you like me to replace the rewire calls with proxyquire or leave as is?

**Comment by theganyo** [comment]
I would prefer consistency, yes. :)

**Comment by theganyo** [comment]
Thanks!

**Pull request merged**
